
const PRIMARY_COLOR = '#022E57';
const PRIMARY_COLOR_LIGHT = '#d4eaf7';
const SECONDARY_COLOR = '#FFEBAD';
const WARNING_COLOR = '#ff983f';
const WARNING_COLOR_LIGHT = '#FFCC99';
const SUCCESS_COLOR = '#24613b';
const DANGER_COLOR = '#EE1D52';
const DANGER_COLOR_LIGHT = '#ff3c63';

const INFO_COLOR = '#6EC3FF';
const PRIMARY_BACKGROUND_COLOR = '#F0F4F4';

const PRIMARY_FONT = 'Viga-Regular';
const SECONDARY_FONT = 'Poppins-Regular';

export {
    PRIMARY_COLOR,
    PRIMARY_COLOR_LIGHT,
    SECONDARY_COLOR,
    WARNING_COLOR,
    WARNING_COLOR_LIGHT,
    SUCCESS_COLOR,
    DANGER_COLOR,
    INFO_COLOR,
    PRIMARY_BACKGROUND_COLOR,
    PRIMARY_FONT,
    SECONDARY_FONT,
    DANGER_COLOR_LIGHT,
};
