
const PRIMARY_COLOR = '#022E57';
const SECONDARY_COLOR = '#FFEBAD';
const WARNING_COLOR = '#ff983f';
const SUCCESS_COLOR = '#24613b';
const DANGER_COLOR = '#EE1D52';
const INFO_COLOR = '#6EC3FF';
const PRIMARY_BACKGROUND_COLOR = '#F0F4F4';
const PRIMARY_FONT = 'Viga-Regular';
const SECONDARY_FONT = 'Poppins-Regular';

export { PRIMARY_COLOR, SECONDARY_COLOR, PRIMARY_BACKGROUND_COLOR, PRIMARY_FONT, SECONDARY_FONT, WARNING_COLOR, SUCCESS_COLOR, DANGER_COLOR, INFO_COLOR};
